apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-image-deployment
  labels:
    app.kubernetes.io/name: demoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: no-image-deployment
  template:
    metadata:
      labels:
        app: no-image-deployment
        visualize: "true"
    spec:
      containers:
        - name: demo-deployment-container
          image: noimage.com/no-such-image
          imagePullPolicy: IfNotPresent

