apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: robusta
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: true
    concurrency: 0
deploy:
  helm:
    releases:
      - name: robusta
        chartPath: helm/robusta
        artifactOverrides:
          runner.image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner

portForward:
- resourceType: deployment
  resourceName: robusta-runner
  port: 5000
  localPort: 5000


profiles:
- name: apple-m1-dev
  build:
    artifacts:
      - image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner
        context: .
        custom:
          buildCommand: ./build_on_apple_m1.sh
    local:
      push: true
      concurrency: 0