import json
from typing import Optional

import hikaru
import pytest
from hikaru import DiffDetail
from hikaru.model.rel_1_26 import Deployment

from robusta.core.model.k8s_operation_type import K8sOperationType
from robusta.integrations.kubernetes.autogenerated.events import KubernetesAnyChangeEvent
from robusta.integrations.kubernetes.base_triggers import (
    DEFAULT_CHANGE_FILTERS,
    DEFAULT_CHANGE_IGNORE,
    DEFAULT_CHANGE_INCLUDE,
    K8sBaseTrigger,
    K8sTriggerChangeFilters,
    _normalize_lifecycle_sleep,
)


class TestK8sBaseTrigger:
    def test_init_no_change_filters(self):
        trigger = K8sBaseTrigger(kind="hello")
        assert trigger.change_filters is None

    @pytest.mark.parametrize(
        "input_change_filters,expected_change_filters",
        [
            ({"include": ["x", "y"], "ignore": ["p", "q"]}, {"include": ["x", "y"], "ignore": ["p", "q"]}),
        ],
    )
    def test_init(self, input_change_filters, expected_change_filters):
        trigger = K8sBaseTrigger(kind="hello", change_filters=K8sTriggerChangeFilters(**input_change_filters))
        assert trigger.change_filters == expected_change_filters

    @pytest.fixture()
    def event(self):
        with open("tests/k8s_change_obj.json") as f:
            data = json.loads(f.read())
        return KubernetesAnyChangeEvent(
            operation=K8sOperationType.UPDATE,
            old_obj=hikaru.from_dict(data, Deployment),
            obj=hikaru.from_dict(data, Deployment),
        )

    @pytest.fixture()
    def trigger(self):
        return K8sBaseTrigger(change_filters=DEFAULT_CHANGE_FILTERS, kind="hello")

    def _set_attr_by_path(self, obj, field_path: str, new_val):
        attr_path = field_path.split(".")
        for attr_name in attr_path[:-1]:
            obj = getattr(obj, attr_name)
        setattr(obj, attr_path[-1], new_val)

    @pytest.mark.parametrize("change_field", [None] + DEFAULT_CHANGE_IGNORE)
    def test_check_change_filters_no_change(self, change_field: Optional[str], event, trigger):
        if change_field:
            self._set_attr_by_path(event.obj, change_field, 987654321)
        assert trigger.check_change_filters(event) is False
        assert hasattr(event, "obj_filtered")
        assert hasattr(event, "old_obj_filtered")
        assert event.filtered_diffs == []

    @pytest.mark.parametrize(
        "change_field,new_value,old_value,expected_change_path,expected_diff_new_value",
        [
            ("spec.selector.matchLabels", {"app": "X"}, "xxx", "Deployment.spec.selector.matchLabels['app']", "X"),
            ("spec.progressDeadlineSeconds", 300, 600, "Deployment.spec.progressDeadlineSeconds", 300),
            ("spec.revisionHistoryLimit", 15, 10, "Deployment.spec.revisionHistoryLimit", 15),
        ],
    )
    def test_check_change_filters_changes(
        self, change_field: str, new_value, old_value, expected_change_path, expected_diff_new_value, event, trigger
    ):
        self._set_attr_by_path(event.obj, change_field, new_value)
        assert trigger.check_change_filters(event) is True
        assert hasattr(event, "obj_filtered")
        assert hasattr(event, "old_obj_filtered")
        assert all(isinstance(diff, DiffDetail) for diff in event.filtered_diffs)
        diff = event.filtered_diffs[0]
        assert diff.formatted_path == expected_change_path
        assert diff.other_value == old_value
        assert diff.value == expected_diff_new_value


class TestNormalizeLifecycleSleep:
    def _wrap_container(self, lifecycle):
        return {
            "spec": {
                "template": {
                    "spec": {
                        "containers": [
                            {"name": "main", "image": "busybox", "lifecycle": lifecycle}
                        ]
                    }
                }
            }
        }

    def test_native_sleep_prestop_is_rewritten_to_exec(self):
        obj = self._wrap_container({"preStop": {"sleep": {"seconds": 10}}})
        _normalize_lifecycle_sleep(obj)
        handler = obj["spec"]["template"]["spec"]["containers"][0]["lifecycle"]["preStop"]
        assert handler == {"exec": {"command": ["sleep", "10"]}}

    def test_native_sleep_poststart_is_rewritten_to_exec(self):
        obj = self._wrap_container({"postStart": {"sleep": {"seconds": 5}}})
        _normalize_lifecycle_sleep(obj)
        handler = obj["spec"]["template"]["spec"]["containers"][0]["lifecycle"]["postStart"]
        assert handler == {"exec": {"command": ["sleep", "5"]}}

    def test_existing_exec_handler_is_left_untouched(self):
        lifecycle = {"preStop": {"exec": {"command": ["sleep", "10"]}}}
        obj = self._wrap_container(lifecycle)
        _normalize_lifecycle_sleep(obj)
        handler = obj["spec"]["template"]["spec"]["containers"][0]["lifecycle"]["preStop"]
        assert handler == {"exec": {"command": ["sleep", "10"]}}

    def test_migration_from_exec_to_native_sleep_yields_no_diff(self):
        # The original bug: switching between equivalent forms generated a notification.
        old_obj = self._wrap_container({"preStop": {"exec": {"command": ["sleep", "10"]}}})
        new_obj = self._wrap_container({"preStop": {"sleep": {"seconds": 10}}})
        _normalize_lifecycle_sleep(old_obj)
        _normalize_lifecycle_sleep(new_obj)
        assert old_obj == new_obj

    def test_handles_init_containers_and_multiple_containers(self):
        obj = {
            "spec": {
                "template": {
                    "spec": {
                        "initContainers": [
                            {"name": "init", "lifecycle": {"preStop": {"sleep": {"seconds": 2}}}}
                        ],
                        "containers": [
                            {"name": "a", "lifecycle": {"preStop": {"sleep": {"seconds": 3}}}},
                            {"name": "b", "lifecycle": {"postStart": {"sleep": {"seconds": 4}}}},
                        ],
                    }
                }
            }
        }
        _normalize_lifecycle_sleep(obj)
        init = obj["spec"]["template"]["spec"]["initContainers"][0]
        a, b = obj["spec"]["template"]["spec"]["containers"]
        assert init["lifecycle"]["preStop"] == {"exec": {"command": ["sleep", "2"]}}
        assert a["lifecycle"]["preStop"] == {"exec": {"command": ["sleep", "3"]}}
        assert b["lifecycle"]["postStart"] == {"exec": {"command": ["sleep", "4"]}}

    def test_no_op_on_unrelated_objects(self):
        obj = {"spec": {"replicas": 3, "selector": {"matchLabels": {"app": "x"}}}}
        snapshot = json.dumps(obj, sort_keys=True)
        _normalize_lifecycle_sleep(obj)
        assert json.dumps(obj, sort_keys=True) == snapshot

    def test_invalid_seconds_value_is_left_untouched(self):
        obj = self._wrap_container({"preStop": {"sleep": {"seconds": "ten"}}})
        _normalize_lifecycle_sleep(obj)
        handler = obj["spec"]["template"]["spec"]["containers"][0]["lifecycle"]["preStop"]
        assert handler == {"sleep": {"seconds": "ten"}}

    def test_exec_takes_precedence_when_both_present(self):
        obj = self._wrap_container(
            {"preStop": {"exec": {"command": ["echo", "hi"]}, "sleep": {"seconds": 7}}}
        )
        _normalize_lifecycle_sleep(obj)
        handler = obj["spec"]["template"]["spec"]["containers"][0]["lifecycle"]["preStop"]
        assert handler == {"exec": {"command": ["echo", "hi"]}, "sleep": {"seconds": 7}}
