from unittest import mock

import pytest
from hikaru.model.rel_1_26 import Node, ObjectMeta, PodSpec
from robusta.core.reporting import FileBlock, MarkdownBlock
from robusta.integrations.kubernetes.autogenerated.events import NodeEvent, PodEvent
from robusta.integrations.kubernetes.custom_models import RobustaPod

from playbooks.robusta_playbooks.dmesg_enrichments import (
    DmesgParams,
    _build_dmesg_command,
    node_dmesg_enricher,
    pod_dmesg_enricher,
)

SINK = "test-sink"


def _get_blocks(event):
    """Return the enrichment blocks added to the event's first finding."""
    finding = event.sink_findings[SINK][0]
    assert len(finding.enrichments) == 1
    return finding.enrichments[0].blocks


@pytest.mark.parametrize(
    "params,expected_command",
    [
        (DmesgParams(), "dmesg"),
        (DmesgParams(lines=100), "dmesg | tail -n 100"),
        (DmesgParams(lines=1), "dmesg | tail -n 1"),
    ],
)
def test_build_dmesg_command(params, expected_command):
    assert _build_dmesg_command(params) == expected_command


def test_node_dmesg_enricher_adds_file_block():
    node = Node(metadata=ObjectMeta(name="test-node"))
    event = NodeEvent(obj=node, named_sinks=[SINK])

    with mock.patch.object(
        RobustaPod, "exec_in_debugger_pod", return_value="[    0.000000] Linux version 5.15.0"
    ) as mock_exec:
        node_dmesg_enricher(event, DmesgParams(lines=50))

    mock_exec.assert_called_once_with("node-dmesg-pod", "test-node", "dmesg | tail -n 50")
    blocks = _get_blocks(event)
    assert len(blocks) == 2
    assert isinstance(blocks[0], MarkdownBlock)
    assert "test-node" in blocks[0].text
    assert isinstance(blocks[1], FileBlock)
    assert blocks[1].filename == "dmesg-test-node.log"
    assert blocks[1].contents == b"[    0.000000] Linux version 5.15.0"


def test_node_dmesg_enricher_no_node():
    event = NodeEvent(obj=None, named_sinks=[SINK])
    with mock.patch.object(RobustaPod, "exec_in_debugger_pod") as mock_exec:
        node_dmesg_enricher(event, DmesgParams())
    mock_exec.assert_not_called()


def test_pod_dmesg_enricher_uses_pod_node():
    pod = RobustaPod(
        metadata=ObjectMeta(name="test-pod", namespace="default"),
        spec=PodSpec(containers=[], nodeName="worker-1"),
    )
    event = PodEvent(obj=pod, named_sinks=[SINK])

    with mock.patch.object(RobustaPod, "exec_in_debugger_pod", return_value="dmesg output") as mock_exec:
        pod_dmesg_enricher(event, DmesgParams())

    mock_exec.assert_called_once_with("node-dmesg-pod", "worker-1", "dmesg")
    blocks = _get_blocks(event)
    assert len(blocks) == 2
    assert isinstance(blocks[1], FileBlock)
    assert blocks[1].filename == "dmesg-worker-1.log"
    assert blocks[1].contents == b"dmesg output"


def test_pod_dmesg_enricher_no_pod():
    event = PodEvent(obj=None, named_sinks=[SINK])
    with mock.patch.object(RobustaPod, "exec_in_debugger_pod") as mock_exec:
        pod_dmesg_enricher(event, DmesgParams())
    mock_exec.assert_not_called()


def test_pod_dmesg_enricher_unscheduled_pod():
    pod = RobustaPod(
        metadata=ObjectMeta(name="pending-pod", namespace="default"),
        spec=PodSpec(containers=[]),
    )
    event = PodEvent(obj=pod, named_sinks=[SINK])
    with mock.patch.object(RobustaPod, "exec_in_debugger_pod") as mock_exec:
        pod_dmesg_enricher(event, DmesgParams())
    mock_exec.assert_not_called()
