{{- if .Values.kubewatch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "robusta.fullname" . }}-kubewatch-config
  namespace: {{ .Release.Namespace }}
data:
  .kubewatch.yaml: |-
    handler:
      cloudevent:
        url: {{ default (printf "http://%s-runner:80/api/handle" (include "robusta.fullname" .)) .Values.kubewatch.overrideUrl | quote }}
{{ toYaml .Values.kubewatch.config | indent 4 }}
{{- end }}
