{{- if (and .Values.openshift.enabled .Values.openshift.createScc) }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "robusta.fullname" . }}-scc
  labels:
    app: {{ include "robusta.fullname" . }}
  annotations:
    kubernetes.io/description: {{ include "robusta.fullname" . }}-scc provides the features required to run robusta
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
priority: {{ .Values.sccPriority }}
readOnlyRootFilesystem: false
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret
{{- end }}
