apiVersion: v1
kind: Secret
metadata:
  name: robusta-playbooks-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  active_playbooks.yaml: |-
    {{ include (ternary "robusta.configfile" "robusta.holmesOnlyConfigfile" (dig "enabled" true .Values.runner)) . | b64enc }}
