import logging
from typing import List

from ..model.pods import pod_most_recent_oom_killed_container
from ...core.playbooks.base_trigger import TriggerEvent
from ...integrations.kubernetes.autogenerated.triggers import (
    PodUpdateTrigger,
    PodChangeEvent,
)
from ...integrations.kubernetes.base_triggers import K8sTriggerEvent
from ...utils.rate_limiter import RateLimiter
from pydantic import BaseModel


class IgnoreSelector(BaseModel):
    """
    :var name_prefix: the name prefix for the pods to ignore containers that's name start with name_prefix
    :var namespace: the name prefix for the containers to ignore that are on pods that start with pod_name_prefix
    , if no pod_name_prefix is defined than all containers with this prefix are ignored on any pod
    """
    name_prefix: str = None
    namespace: str = None


class PodOOMKilledTrigger(PodUpdateTrigger):
    """
    :var rate_limit: Limit firing to once every `rate_limit` seconds
    """

    rate_limit: int = 0
    ignore_selectors: List[IgnoreSelector] = None

    def __init__(
            self,
            name_prefix: str = None,
            namespace_prefix: str = None,
            labels_selector: str = None,
            rate_limit: int = 0,
            ignore_selectors: List[IgnoreSelector] = None
    ):
        super().__init__(
            name_prefix=name_prefix,
            namespace_prefix=namespace_prefix,
            labels_selector=labels_selector,
        )
        self.rate_limit = rate_limit
        self.ignore_selectors = ignore_selectors

    def should_fire(self, event: TriggerEvent, playbook_id: str):
        should_fire = super().should_fire(event, playbook_id)
        if not should_fire:
            return should_fire

        if not isinstance(event, K8sTriggerEvent):
            return False

        exec_event = self.build_execution_event(event, {})

        if not isinstance(exec_event, PodChangeEvent):
            return False

        pod = exec_event.get_pod()
        if self.ignore_selectors:
            for selector in self.ignore_selectors:
                namespace = None if "namespace" not in selector else selector["namespace"]
                name_prefix = None if "name_prefix" not in selector else selector["name_prefix"]
                if not namespace and not name_prefix:
                    logging.info("case 4")
                    # bad config
                    continue
                namespace_match = namespace and namespace == pod.metadata.namespace
                name_prefix_match = name_prefix and pod.metadata.name.startswith(name_prefix)
                if namespace and not namespace_match:
                    #this selector isnt the current namespace
                    continue
                if name_prefix_match and (namespace_match or not namespace):
                    # Pod name Matched + (namespace match or no namespace defined)
                    return False
                if namespace_match and not name_prefix:
                    # Namespace Match and no pod name specified
                    return False

        oom_killed = pod_most_recent_oom_killed_container(pod, only_current_state=True)

        if not oom_killed or not oom_killed.state:
            return False

        # Perform a rate limit for this pod according to the rate_limit parameter
        name = (
            pod.metadata.ownerReferences[0].name
            if pod.metadata.ownerReferences
            else pod.metadata.name
        )
        namespace = pod.metadata.namespace
        return RateLimiter.mark_and_test(
            f"PodOOMKilledTrigger_{playbook_id}",
            namespace + ":" + name,
            self.rate_limit,
        )
