import logging
from typing import List

from ..model.pods import pod_most_recent_oom_killed_container
from ...core.playbooks.base_trigger import TriggerEvent
from ...integrations.kubernetes.autogenerated.triggers import (
    PodUpdateTrigger,
    PodChangeEvent,
)
from ...integrations.kubernetes.base_triggers import K8sTriggerEvent
from ...utils.rate_limiter import RateLimiter
from pydantic import BaseModel


class IgnoreSelector(BaseModel):
    pod_name_prefix: str = None
    container_name_prefix: str = None


class PodOOMKilledTrigger(PodUpdateTrigger):
    """
    :var rate_limit: Limit firing to once every `rate_limit` seconds
    """

    rate_limit: int = 0
    ignore_selectors: List[IgnoreSelector] = None

    def __init__(
            self,
            name_prefix: str = None,
            namespace_prefix: str = None,
            labels_selector: str = None,
            rate_limit: int = 0,
            ignore_selectors: List[IgnoreSelector] = None
    ):
        super().__init__(
            name_prefix=name_prefix,
            namespace_prefix=namespace_prefix,
            labels_selector=labels_selector,
        )
        self.rate_limit = rate_limit
        self.ignore_selectors = ignore_selectors

    def should_fire(self, event: TriggerEvent, playbook_id: str):
        should_fire = super().should_fire(event, playbook_id)
        if not should_fire:
            return should_fire

        if not isinstance(event, K8sTriggerEvent):
            return False

        exec_event = self.build_execution_event(event, {})

        if not isinstance(exec_event, PodChangeEvent):
            return False

        pod = exec_event.get_pod()
        containers = pod.status.containerStatuses + pod.status.initContainerStatuses
        if self.ignore_selectors:
            for selector in self.ignore_selectors:
                if selector["pod_name_prefix"] and not pod.metadata.name.startswith(selector["pod_name_prefix"]):
                    #this selector isnt the current pod
                    continue
                if not selector["container_name_prefix"]:
                    # this selector is for all containers on this pod
                    return False
                containers = [container for container in containers if not container.name.startswith(selector["container_name_prefix"])]
        mem_eater = [container for container in containers if
                         container.name.startswith('memory-eater')]
        if len(mem_eater) > 0:
            logging.info("bad")
        oom_killed = pod_most_recent_oom_killed_container(pod, containers=containers, only_current_state=True)

        if not oom_killed or not oom_killed.state:
            return False

        # Perform a rate limit for this pod according to the rate_limit parameter
        name = (
            pod.metadata.ownerReferences[0].name
            if pod.metadata.ownerReferences
            else pod.metadata.name
        )
        namespace = pod.metadata.namespace
        return RateLimiter.mark_and_test(
            f"PodOOMKilledTrigger_{playbook_id}",
            namespace + ":" + name,
            self.rate_limit,
        )
