# This file was autogenerated. Do not edit.

from dataclasses import dataclass
from typing import Union, Optional
from ..base_event import K8sBaseEvent
from ..custom_models import RobustaPod, RobustaDeployment
from hikaru.model.rel_1_16.v1 import Pod as v1Pod
from hikaru.model.rel_1_16.v1 import ReplicaSet as v1ReplicaSet
from hikaru.model.rel_1_16.v1 import DaemonSet as v1DaemonSet
from hikaru.model.rel_1_16.v1 import Deployment as v1Deployment
from hikaru.model.rel_1_16.v1 import StatefulSet as v1StatefulSet
from hikaru.model.rel_1_16.v1 import Service as v1Service
from hikaru.model.rel_1_16.v1 import ConfigMap as v1ConfigMap
from hikaru.model.rel_1_16.v1 import Event as v1Event
from hikaru.model.rel_1_16.v1 import (
    HorizontalPodAutoscaler as v1HorizontalPodAutoscaler,
)
from hikaru.model.rel_1_16.v1 import Node as v1Node
from hikaru.model.rel_1_16.v1 import ClusterRole as v1ClusterRole
from hikaru.model.rel_1_16.v1 import Job as v1Job
from hikaru.model.rel_1_16.v2beta1 import Pod as v2beta1Pod
from hikaru.model.rel_1_16.v2beta1 import ReplicaSet as v2beta1ReplicaSet
from hikaru.model.rel_1_16.v2beta1 import DaemonSet as v2beta1DaemonSet
from hikaru.model.rel_1_16.v2beta1 import Deployment as v2beta1Deployment
from hikaru.model.rel_1_16.v2beta1 import StatefulSet as v2beta1StatefulSet
from hikaru.model.rel_1_16.v2beta1 import Service as v2beta1Service
from hikaru.model.rel_1_16.v2beta1 import ConfigMap as v2beta1ConfigMap
from hikaru.model.rel_1_16.v2beta1 import Event as v2beta1Event
from hikaru.model.rel_1_16.v2beta1 import (
    HorizontalPodAutoscaler as v2beta1HorizontalPodAutoscaler,
)
from hikaru.model.rel_1_16.v2beta1 import Node as v2beta1Node
from hikaru.model.rel_1_16.v2beta1 import ClusterRole as v2beta1ClusterRole
from hikaru.model.rel_1_16.v2beta1 import Job as v2beta1Job
from hikaru.model.rel_1_16.v2beta2 import Pod as v2beta2Pod
from hikaru.model.rel_1_16.v2beta2 import ReplicaSet as v2beta2ReplicaSet
from hikaru.model.rel_1_16.v2beta2 import DaemonSet as v2beta2DaemonSet
from hikaru.model.rel_1_16.v2beta2 import Deployment as v2beta2Deployment
from hikaru.model.rel_1_16.v2beta2 import StatefulSet as v2beta2StatefulSet
from hikaru.model.rel_1_16.v2beta2 import Service as v2beta2Service
from hikaru.model.rel_1_16.v2beta2 import ConfigMap as v2beta2ConfigMap
from hikaru.model.rel_1_16.v2beta2 import Event as v2beta2Event
from hikaru.model.rel_1_16.v2beta2 import (
    HorizontalPodAutoscaler as v2beta2HorizontalPodAutoscaler,
)
from hikaru.model.rel_1_16.v2beta2 import Node as v2beta2Node
from hikaru.model.rel_1_16.v2beta2 import ClusterRole as v2beta2ClusterRole
from hikaru.model.rel_1_16.v2beta2 import Job as v2beta2Job


@dataclass
class KubernetesAnyEvent(K8sBaseEvent):
    obj: Optional[
        Union[
            v2beta1ClusterRole,
            v2beta2DaemonSet,
            v1Service,
            v2beta2Service,
            v2beta2Event,
            RobustaPod,
            v2beta2HorizontalPodAutoscaler,
            v2beta1DaemonSet,
            v1ClusterRole,
            v2beta1StatefulSet,
            v1Node,
            v2beta2Job,
            v2beta1Job,
            v2beta2ConfigMap,
            v1ConfigMap,
            v2beta2ReplicaSet,
            v1DaemonSet,
            v2beta1HorizontalPodAutoscaler,
            v2beta1ReplicaSet,
            v2beta1Node,
            v2beta1Service,
            v2beta1ConfigMap,
            v2beta2ClusterRole,
            RobustaDeployment,
            v1StatefulSet,
            v1Job,
            v2beta2Node,
            v1ReplicaSet,
            v1HorizontalPodAutoscaler,
            v2beta1Event,
            v2beta2StatefulSet,
            v1Event,
        ]
    ] = None
    old_obj: Optional[
        Union[
            v2beta1ClusterRole,
            v2beta2DaemonSet,
            v1Service,
            v2beta2Service,
            v2beta2Event,
            RobustaPod,
            v2beta2HorizontalPodAutoscaler,
            v2beta1DaemonSet,
            v1ClusterRole,
            v2beta1StatefulSet,
            v1Node,
            v2beta2Job,
            v2beta1Job,
            v2beta2ConfigMap,
            v1ConfigMap,
            v2beta2ReplicaSet,
            v1DaemonSet,
            v2beta1HorizontalPodAutoscaler,
            v2beta1ReplicaSet,
            v2beta1Node,
            v2beta1Service,
            v2beta1ConfigMap,
            v2beta2ClusterRole,
            RobustaDeployment,
            v1StatefulSet,
            v1Job,
            v2beta2Node,
            v1ReplicaSet,
            v1HorizontalPodAutoscaler,
            v2beta1Event,
            v2beta2StatefulSet,
            v1Event,
        ]
    ] = None


@dataclass
class PodEvent(KubernetesAnyEvent):
    obj: Optional[RobustaPod] = None
    old_obj: Optional[RobustaPod] = None


@dataclass
class ReplicaSetEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1ReplicaSet, v2beta1ReplicaSet, v2beta2ReplicaSet]] = None
    old_obj: Optional[Union[v1ReplicaSet, v2beta1ReplicaSet, v2beta2ReplicaSet]] = None


@dataclass
class DaemonSetEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1DaemonSet, v2beta1DaemonSet, v2beta2DaemonSet]] = None
    old_obj: Optional[Union[v1DaemonSet, v2beta1DaemonSet, v2beta2DaemonSet]] = None


@dataclass
class DeploymentEvent(KubernetesAnyEvent):
    obj: Optional[RobustaDeployment] = None
    old_obj: Optional[RobustaDeployment] = None


@dataclass
class StatefulSetEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1StatefulSet, v2beta1StatefulSet, v2beta2StatefulSet]] = None
    old_obj: Optional[
        Union[v1StatefulSet, v2beta1StatefulSet, v2beta2StatefulSet]
    ] = None


@dataclass
class ServiceEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1Service, v2beta1Service, v2beta2Service]] = None
    old_obj: Optional[Union[v1Service, v2beta1Service, v2beta2Service]] = None


@dataclass
class ConfigMapEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1ConfigMap, v2beta1ConfigMap, v2beta2ConfigMap]] = None
    old_obj: Optional[Union[v1ConfigMap, v2beta1ConfigMap, v2beta2ConfigMap]] = None


@dataclass
class EventEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1Event, v2beta1Event, v2beta2Event]] = None
    old_obj: Optional[Union[v1Event, v2beta1Event, v2beta2Event]] = None


@dataclass
class HorizontalPodAutoscalerEvent(KubernetesAnyEvent):
    obj: Optional[
        Union[
            v1HorizontalPodAutoscaler,
            v2beta1HorizontalPodAutoscaler,
            v2beta2HorizontalPodAutoscaler,
        ]
    ] = None
    old_obj: Optional[
        Union[
            v1HorizontalPodAutoscaler,
            v2beta1HorizontalPodAutoscaler,
            v2beta2HorizontalPodAutoscaler,
        ]
    ] = None


@dataclass
class NodeEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1Node, v2beta1Node, v2beta2Node]] = None
    old_obj: Optional[Union[v1Node, v2beta1Node, v2beta2Node]] = None


@dataclass
class ClusterRoleEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1ClusterRole, v2beta1ClusterRole, v2beta2ClusterRole]] = None
    old_obj: Optional[
        Union[v1ClusterRole, v2beta1ClusterRole, v2beta2ClusterRole]
    ] = None


@dataclass
class JobEvent(KubernetesAnyEvent):
    obj: Optional[Union[v1Job, v2beta1Job, v2beta2Job]] = None
    old_obj: Optional[Union[v1Job, v2beta1Job, v2beta2Job]] = None


KIND_TO_EVENT_CLASS = {
    "Pod": PodEvent,
    "ReplicaSet": ReplicaSetEvent,
    "DaemonSet": DaemonSetEvent,
    "Deployment": DeploymentEvent,
    "StatefulSet": StatefulSetEvent,
    "Service": ServiceEvent,
    "ConfigMap": ConfigMapEvent,
    "Event": EventEvent,
    "HorizontalPodAutoscaler": HorizontalPodAutoscalerEvent,
    "Node": NodeEvent,
    "ClusterRole": ClusterRoleEvent,
    "Job": JobEvent,
}
