# This file was autogenerated. Do not edit.

from robusta.integrations.kubernetes.autogenerated.v1.models import KIND_TO_MODEL_CLASS as v1
VERSION_KIND_TO_MODEL_CLASS = {
    "v1": v1
}


def get_api_version(apiVersion: str):
    if "/" in apiVersion:
        apiVersion = apiVersion.split("/")[1]
    return VERSION_KIND_TO_MODEL_CLASS.get(apiVersion)
