import uuid
from enum import Enum
from pydantic.main import BaseModel
from typing import List, Dict, Optional, Union
from ...integrations.kubernetes.autogenerated.events import *
from ..model.env_vars import ROBUSTA_UI_DOMAIN
from ..reporting.consts import FindingSubjectType, FindingSource, FindingType
from ...core.discovery.top_service_resolver import TopServiceResolver


class BaseBlock(BaseModel):
    hidden: bool = False


class FindingSeverity(Enum):
    INFO = 1
    LOW = 2
    MEDIUM = 3
    HIGH = 4


class Enrichment:
    # These is the actual enrichment data
    blocks: List[BaseBlock] = []
    # General purpose rendering flags, that can be used by specific sinks
    annotations: Dict[str, str] = {}

    def __init__(self, blocks: List[BaseBlock], annotations=None):
        if annotations is None:
            annotations = {}
        self.blocks = blocks
        self.annotations = annotations

    def __str__(self):
        return f"annotations: {self.annotations} Enrichment: {self.blocks} "


class FindingSubject:
    def __init__(
        self,
        name: str = None,
        subject_type: FindingSubjectType = FindingSubjectType.TYPE_NONE,
        namespace: str = None,
        node: str = None
    ):
        self.name = name
        self.subject_type = subject_type
        self.namespace = namespace
        self.node = node


class KubeObjFindingSubject(FindingSubject):
    UnionKubernetesObjects = Optional[Union[
        RobustaDeployment, RobustaJob, RobustaPod, v1ClusterRole, v1ClusterRoleBinding, v1DaemonSet, v1Event,
        v1HorizontalPodAutoscaler, v1Namespace, v1Node, v1ReplicaSet, v1Service, v1ServiceAccount, v1StatefulSet,
        v2beta1ClusterRole, v2beta1ClusterRoleBinding, v2beta1DaemonSet, v2beta1Event, v2beta1HorizontalPodAutoscaler,
        v2beta1Namespace, v2beta1Node, v2beta1ReplicaSet, v2beta1Service, v2beta1ServiceAccount, v2beta1StatefulSet,
        v2beta2ClusterRole, v2beta2ClusterRoleBinding, v2beta2DaemonSet, v2beta2Event, v2beta2HorizontalPodAutoscaler,
        v2beta2Namespace, v2beta2Node, v2beta2ReplicaSet, v2beta2Service, v2beta2ServiceAccount, v2beta2StatefulSet]]

    def __init__(self, obj: UnionKubernetesObjects = None, finding_subject_type: FindingSubjectType = None):
        if not finding_subject_type:
            finding_subject_type = FindingSubjectType.from_kind(obj.kind)
        super(KubeObjFindingSubject, self).__init__(
            obj.metadata.name,
            finding_subject_type,
            obj.metadata.namespace,
            KubeObjFindingSubject.get_node_name(obj)
        )

    @staticmethod
    def get_node_name(obj: UnionKubernetesObjects):
        try:
            kind = obj.kind
            if kind == "node":
                return obj.metadata.name
            elif kind == "pod":
                return obj.spec.nodeName
            elif kind == "job":
                return None
        except:
            pass
        return None


class PodFindingSubject(FindingSubject):
    def __init__(
        self,
        pod: RobustaPod = None
    ):
        super(PodFindingSubject, self).__init__(
            pod.metadata.name,
            FindingSubjectType.TYPE_POD,
            pod.metadata.namespace,
            pod.spec.nodeName
        )

class Finding:
    """
    A Finding represents an event that should be sent to sinks.
    """

    def __init__(
        self,
        title: str,
        aggregation_key: str,
        severity: FindingSeverity = FindingSeverity.INFO,
        source: FindingSource = FindingSource.NONE,
        description: str = None,
        subject: FindingSubject = FindingSubject(),
        finding_type: FindingType = FindingType.ISSUE,
        failure: bool = True,
    ) -> None:
        self.id: uuid = uuid.uuid4()
        self.title = title
        self.finding_type = finding_type
        self.failure = failure
        self.description = description
        self.source = source
        self.aggregation_key = aggregation_key
        self.severity = severity
        self.category = None  # TODO fill real category
        self.subject = subject
        self.enrichments: List[Enrichment] = []
        self.service_key = TopServiceResolver.guess_service_key(
            name=subject.name,
            namespace=subject.namespace
        )
        uri_path = f"services/{self.service_key}?tab=grouped" if self.service_key else "graphs"
        self.investigate_uri = f"{ROBUSTA_UI_DOMAIN}/{uri_path}"

    def add_enrichment(self, enrichment_blocks: List[BaseBlock], annotations=None):
        if not enrichment_blocks:
            return
        if annotations is None:
            annotations = {}
        self.enrichments.append(Enrichment(enrichment_blocks, annotations))

    def __str__(self):
        return f"title: {self.title} desc: {self.description} severity: {self.severity} sub-name: {self.subject.name} sub-type:{self.subject.subject_type.value} enrich: {self.enrichments}"
