#!/bin/sh

function cleanup() {
    tput cnorm
}

trap cleanup EXIT

tput civis
spinner()
{
    local pid=$!
    local delay=0.5
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "\b\b\b\b"
}

if [[ "$(docker images -q  us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-cli 2> /dev/null)" == "" ]]; then
  echo 'please wait'
  docker pull  us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-cli > /dev/null 2>&1 & spinner
fi

COMMANDS=$@
if [[ -z "$COMMANDS" ]]; then
   COMMANDS="--help"
fi

docker run -it --rm --net host -v ${PWD}:/workingdir -w=/workingdir -v ~/.kube:/root/.kube us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-cli robusta $COMMANDS
