name: Automated message for issues
on:
  issues:
    types:
      - opened
jobs:
  build:
    name: Welcome new contributor 🎉
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi 👋, thanks for opening an issue! Please note, it may take some time for us to respond, but we'll get back to you as soon as we can! \n\n- 💬 **Slack Community:** Join Robusta team and other contributors on Slack [here](https://bit.ly/robusta-slack).\n- 📖 **Docs:** Find our documentation [here](https://docs.robusta.dev/master/).\n- 🎥 **YouTube Channel:** Watch our videos [here](https://www.youtube.com/@RobustaDev)."
