on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  has-secrets:
    name: Check Secrets
    runs-on: ubuntu-latest
    steps:
    - id: semgrep
      env:
        HAS_SECRET_ACCESS: ${{ secrets.HAS_SECRET_ACCESS }}
      if: ${{ env.HAS_SECRET_ACCESS != '' }}
      run: echo '::set-output name=semgrep::true'
    outputs:
      semgrep: ${{ steps.semgrep.outputs.semgrep }}
  semgrep:
    name: Semgrep Scan
    needs: [has-secrets]
    if: needs.has-secrets.outputs.semgrep
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 1560
