name: Test robusta-cli installation package

on: [push, pull_request]

jobs:
    build_package:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Build and install package
          run: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            poetry build
            pip3 install ./dist/robusta_cli-0.0.0-py3-none-any.whl
        - name: Upload robusta package artifact
          uses: actions/upload-artifact@v2
          with:
            name: robusta-pkg
            path: dist/robusta_cli-0.0.0-py3-none-any.whl


    # we use a totally separate job for testing the package because we want an environment which is free of all the
    # dependencies that poetry itself requires
    test_package:
      needs: build_package
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ 3.7, 3.8, 3.9 ]

      steps:
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Download robusta-pkg
          uses: actions/download-artifact@v2
          with:
            name: robusta-pkg
        - name: Install and test robusta cli
          run: |
            ls
            pip3 install robusta_cli-0.0.0-py3-none-any.whl
            robusta version
